import { Crosshair, MapPin, Plus, Store } from 'lucide-react';
import { useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import { addArea, addOutlet, getAllOutlets, getAreas } from '../services/outletService';
import type { Area, Outlet } from '../types';

export default function Areas() {
  const [areas, setAreas] = useState<Area[]>([]); const [outlets, setOutlets] = useState<Outlet[]>([]); const [areaName, setAreaName] = useState('');
  const [form, setForm] = useState({ areaId: '', shopName: '', contactNumber: '', gst: '', address: '', latitude: undefined as number | undefined, longitude: undefined as number | undefined });
  useEffect(() => { Promise.all([getAreas(), getAllOutlets()]).then(([areaData, outletData]) => { setAreas(areaData); setOutlets(outletData); }).catch((error) => toast.error(error instanceof Error ? error.message : 'Could not load outlets')); }, []);
  async function createArea() { if (!areaName.trim()) return; try { const id = await addArea(areaName); const area = { id, name: areaName.trim() } as Area; setAreas((current) => [...current, area].sort((a, b) => a.name.localeCompare(b.name))); setForm((current) => ({ ...current, areaId: id })); setAreaName(''); toast.success('Area added'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not add area'); } }
  function useLocation() { if (!navigator.geolocation) return toast.error('Location is not available in this browser'); navigator.geolocation.getCurrentPosition((position) => { const { latitude, longitude } = position.coords; setForm((current) => ({ ...current, latitude, longitude, address: current.address || `Location: ${latitude.toFixed(6)}, ${longitude.toFixed(6)}` })); toast.success('Current location added. You can refine the address below.'); }, () => toast.error('Location permission was not granted')); }
  async function createOutlet() { const area = areas.find((item) => item.id === form.areaId); if (!area || !form.shopName.trim() || !/^[6-9]\d{9}$/.test(form.contactNumber) || !form.address.trim()) return toast.error('Select an area and enter shop name, valid contact number, and address'); try { const outletData = { ...form, areaName: area.name, shopName: form.shopName.trim(), contactNumber: form.contactNumber.trim(), gst: form.gst.trim(), address: form.address.trim() }; const id = await addOutlet(outletData); setOutlets((current) => [...current, { ...outletData, id } as Outlet]); setForm({ areaId: form.areaId, shopName: '', contactNumber: '', gst: '', address: '', latitude: undefined, longitude: undefined }); toast.success('Outlet added'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not add outlet'); } }
  return <div className="space-y-4 sm:space-y-5"><div><h1 className="text-xl font-black tracking-tight sm:text-2xl">Areas & Outlets</h1><p className="text-sm text-slate-500 dark:text-slate-400">Organize shops by area so sales visits are quick to start.</p></div><section className="panel flex flex-col gap-3 sm:flex-row"><input className="field" placeholder="Area name, e.g. Hadapsar" value={areaName} onChange={(event) => setAreaName(event.target.value)} /><button className="btn-primary shrink-0" onClick={createArea}><Plus size={18} />Add Area</button></section><section className="panel grid gap-3 md:grid-cols-2"><select className="field" value={form.areaId} onChange={(event) => setForm({ ...form, areaId: event.target.value })}><option value="">Select area</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select><input className="field" placeholder="Shop name" value={form.shopName} onChange={(event) => setForm({ ...form, shopName: event.target.value })} /><input className="field" placeholder="Contact number" value={form.contactNumber} onChange={(event) => setForm({ ...form, contactNumber: event.target.value })} /><input className="field" placeholder="GST number (optional)" value={form.gst} onChange={(event) => setForm({ ...form, gst: event.target.value })} /><div className="md:col-span-2"><label className="label">Address</label><div className="flex gap-2"><input className="field" placeholder="Shop address" value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} /><button className="icon-btn shrink-0" onClick={useLocation} title="Use current location"><Crosshair size={18} /></button></div></div><button className="btn-primary md:col-span-2" onClick={createOutlet}><Store size={18} />Add Outlet</button></section><section className="panel"><h2 className="mb-3 text-lg font-black">Available Outlets</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{outlets.map((outlet) => <div key={outlet.id} className="rounded-lg border border-slate-200 p-3 dark:border-slate-800"><p className="font-black">{outlet.shopName}</p><p className="mt-1 text-sm font-semibold text-brand">{outlet.areaName}</p><p className="mt-2 text-sm text-slate-500"><MapPin className="mr-1 inline" size={14} />{outlet.address}</p><p className="mt-1 text-sm text-slate-500">{outlet.contactNumber}</p></div>)}</div></section></div>;
}
