import { ArrowRight, Clock3, MapPin, Store } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import { getAreaVisits, getAreas, getOutlets } from '../services/outletService';
import type { Area, Outlet, VisitRecord } from '../types';

const sevenDaysAgo = () => Date.now() - 7 * 24 * 60 * 60 * 1000;
const visitTime = (visit?: VisitRecord) => visit?.visitedAt?.toDate?.().getTime() ?? 0;

export default function Visit() {
  const navigate = useNavigate();
  const [areas, setAreas] = useState<Area[]>([]); const [selectedArea, setSelectedArea] = useState(''); const [outlets, setOutlets] = useState<Outlet[]>([]); const [visits, setVisits] = useState<VisitRecord[]>([]); const [loading, setLoading] = useState(false);
  useEffect(() => { getAreas().then(setAreas).catch((error) => toast.error(error instanceof Error ? error.message : 'Could not load areas')); }, []);
  useEffect(() => { if (!selectedArea) { setOutlets([]); setVisits([]); return; } setLoading(true); Promise.all([getOutlets(selectedArea), getAreaVisits(selectedArea)]).then(([outletData, visitData]) => { setOutlets(outletData); setVisits(visitData); }).catch((error) => toast.error(error instanceof Error ? error.message : 'Could not load visit data')).finally(() => setLoading(false)); }, [selectedArea]);
  const latestVisits = useMemo(() => { const result = new Map<string, VisitRecord>(); visits.forEach((visit) => { if (!result.has(visit.outletId) || visitTime(result.get(visit.outletId)) < visitTime(visit)) result.set(visit.outletId, visit); }); return result; }, [visits]);
  const visitedThisWeek = outlets.filter((outlet) => visitTime(latestVisits.get(outlet.id ?? '')) >= sevenDaysAgo()).length; const dueOutlets = outlets.length - visitedThisWeek;
  return <div className="space-y-4 sm:space-y-5"><div><h1 className="text-xl font-black tracking-tight sm:text-2xl">Visit</h1><p className="text-sm text-slate-500 dark:text-slate-400">Record outlet visits, notes, and orders.</p></div><section className="panel"><label className="label">Area</label><select className="field max-w-xl" value={selectedArea} onChange={(event) => setSelectedArea(event.target.value)}><option value="">Select an area</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select>{selectedArea ? <div className="mt-4 grid grid-cols-3 gap-2 sm:max-w-xl"><Count label="Outlets" value={outlets.length} /><Count label="Visited (7d)" value={visitedThisWeek} /><Count label="Due now" value={dueOutlets} alert={dueOutlets > 0} /></div> : null}</section>{selectedArea ? <section className="panel"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black">Outlets</h2><span className="text-xs font-semibold text-slate-500">Tap to add visit note</span></div>{loading ? <p className="text-sm text-slate-500">Loading outlets...</p> : outlets.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{outlets.map((outlet) => { const latest = latestVisits.get(outlet.id ?? ''); const due = visitTime(latest) < sevenDaysAgo(); return <button key={outlet.id} className="rounded-lg border border-slate-200 p-4 text-left transition hover:border-brand hover:bg-emerald-50 dark:border-slate-800 dark:hover:bg-slate-800" onClick={() => navigate(`/visit/${outlet.id}`)}><div className="flex items-start justify-between gap-2"><div><p className="font-black">{outlet.shopName}</p><p className="mt-1 text-sm font-semibold text-brand">{outlet.areaName}</p></div><ArrowRight size={18} /></div><p className="mt-3 text-sm text-slate-500"><MapPin className="mr-1 inline" size={14} />{outlet.address}</p><p className="mt-2 text-sm font-semibold">{outlet.contactNumber}</p><p className={`mt-3 flex items-center gap-1 text-xs font-bold ${due ? 'text-amber-600' : 'text-brand'}`}><Clock3 size={14} />{due ? 'Due: no visit in last 7 days' : `Visited ${latest!.visitedAt.toDate().toLocaleDateString('en-IN')}`}</p></button>; })}</div> : <div className="flex items-center gap-2 text-sm text-slate-500"><Store size={18} />No outlets in this area yet.</div>}</section> : null}</div>;
}
function Count({ label, value, alert }: { label: string; value: number; alert?: boolean }) { return <div className={`rounded-lg p-3 text-center ${alert ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200'}`}><p className="text-lg font-black">{value}</p><p className="text-[10px] font-bold uppercase">{label}</p></div>; }
