import { ArrowLeft, ClipboardList, FilePlus2, MapPin, Save } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'react-toastify';
import { getOutlet, getOutletVisits, saveVisit } from '../services/outletService';
import { useAuth } from '../contexts/AuthContext';
import type { Outlet, VisitRecord } from '../types';

export default function VisitNote() {
  const { outletId } = useParams(); const navigate = useNavigate(); const { user, employee } = useAuth();
  const [outlet, setOutlet] = useState<Outlet | null>(null); const [history, setHistory] = useState<VisitRecord[]>([]); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!outletId) return; Promise.all([getOutlet(outletId), getOutletVisits(outletId)]).then(([outletData, visits]) => { setOutlet(outletData); setHistory(visits); }).catch(() => toast.error('Could not load outlet history')); }, [outletId]);
  async function save(hasOrder: boolean) { if (!outlet?.id || !user) return; setSaving(true); try { await saveVisit({ outletId: outlet.id, outletName: outlet.shopName, areaId: outlet.areaId, areaName: outlet.areaName, note: note.trim(), hasOrder, createdBy: user.uid, employeeName: employee?.name ?? user.email ?? 'Employee' }); toast.success('Visit saved'); navigate(hasOrder ? `/invoice/new?outletId=${outlet.id}` : '/visit'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not save visit'); } finally { setSaving(false); } }
  if (!outlet) return <p className="text-sm text-slate-500">Loading outlet...</p>;
  return <div className="mx-auto max-w-2xl space-y-4"><button className="btn-secondary" onClick={() => navigate('/visit')}><ArrowLeft size={18} />Back to visits</button><section className="panel"><h1 className="text-xl font-black">Visit note</h1><p className="mt-2 font-bold text-brand">{outlet.shopName}</p><p className="mt-1 text-sm text-slate-500"><MapPin className="mr-1 inline" size={14} />{outlet.address}</p></section><section className="panel"><label className="label">Visit information</label><textarea className="field min-h-36" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Discussion, stock requirement, follow-up, payment note..." /><div className="mt-4 grid gap-3 sm:grid-cols-2"><button className="btn-secondary" disabled={saving} onClick={() => save(false)}><Save size={18} />Save visit only</button><button className="btn-primary" disabled={saving} onClick={() => save(true)}><FilePlus2 size={18} />{saving ? 'Saving...' : 'Save & create invoice'}</button></div></section><section className="panel"><div className="mb-4 flex items-center gap-2"><ClipboardList className="text-brand" size={20} /><h2 className="text-lg font-black">Previous visits</h2><span className="ml-auto text-xs font-bold text-slate-500">{history.length} records</span></div>{history.length ? <div className="space-y-3">{history.map((visit) => <article key={visit.id} className="rounded-lg border border-slate-200 p-3 dark:border-slate-800"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-bold">{visit.visitedAt?.toDate?.().toLocaleString('en-IN') ?? 'Just now'}</p><span className={`rounded-full px-2 py-1 text-xs font-bold ${visit.hasOrder ? 'bg-emerald-50 text-brand' : 'bg-slate-100 text-slate-600'}`}>{visit.hasOrder ? 'Order created' : 'No order'}</span></div>{visit.note ? <p className="mt-2 whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300">{visit.note}</p> : <p className="mt-2 text-sm italic text-slate-400">No note added</p>}<p className="mt-2 text-xs font-semibold text-slate-500">Recorded by {visit.employeeName}</p></article>)}</div> : <p className="text-sm text-slate-500">No previous visits recorded for this outlet.</p>}</section></div>;
}
